### ISSUE TITLE
Does not work in Firefox (Linux Manjaro)

### ISSUE THREAD

**Issue by dmitrytrofim** [Vahan0799/infinite-marquee#2]
Hi! It's a cool library, but it doesn't work in firefox. If you correct it, it will be super. I'm sorry if I'm not clear, I don't know English well :)

**Comment by Vahan0799** [comment]
Hi @dmitrytrofim , thanks for the feedback :)

I just ran a few tests on Firefox and it does work correctly. 
Can you please share your HTML Marquee structure and JS config of it please?

If Marquee structure is rendered correctly from JS and animation won't start, that means something from CSS is missing, if not then there might be an error above Marquee configs that stops the script. 

P.S. На русском тоже можно)

**Comment by dmitrytrofim** [comment]
Я сижу на Linux Manjaro. Эта проблема наблюдается в Firefox и Gnome Web. Но поскольку на линуксе сидит мало пользователей, а в этих браузерах и того меньше, то думаю эта проблема несущественна. Но если кто-то захочет скрыть проблему в этих браузерах, то могу порекомендовать свое решение. Я бегущую строку скрыл через opacity: 0; pointer-events: none; Затем через event animationstart делаю opacity: 1; Как итог, во всех браузерах, где скрипт срабатывает, все ок. А где нет, то бегущая строка скрыта и тоже все ок..

Скрин с firefox (linux manjaro)
![trouble](https://github.com/Vahan0799/infinite-marquee/assets/78739257/2df07f66-b793-420e-9321-3055dfb75ce2)

**Comment by Vahan0799** [comment]
@dmitrytrofim Найти причину мне не удалось, проверил я в Ubuntu, Mac и старые версии через BrowserStack и такого не было. 

Я выпустил новую 1.0.8 версию где добавил Debugger через консоль чтоб найти в каком именно моменте код перестает работать. 

Демку тоже обновил. Попробуй посмотреть консоль в демке, при полном успешном запуске там должно быть 6 логов.

**Comment by dmitrytrofim** [comment]
Вот такая история. Ну а в целом, если это только эти 2 браузера, то проблем вообще не вижу. Спасибо за обратную связь! И вопрос. Можешь Debugger сделать опциональным? А то не хочется чтобы он выдавал сообщения когда не надо)

![Снимок экрана от 2024-02-14 16-00-19](https://github.com/Vahan0799/infinite-marquee/assets/78739257/3e1ccef7-473e-4c68-8d34-1f0526e0ca95)

**Comment by Vahan0799** [comment]
@dmitrytrofim Анимация не запускается так как у тебя на компе или в браузере заглушены анимации. Это медиа запрос с CSS prefers-reduced-motion и у тебя оно стоит на reduce значении. Это и есть причина ошибки. 

Такое бывает даже при включенном Low Power состоянии для ноутбука или смартфона.

Я поправлю стили чтоб в таком случае они нормально смотрелись а вот анимацию это и должно заглушить так как есть пользователи которые не любят такое. Багов тут нет. 

Да этот debug поправлю и скажу.

**Comment by dmitrytrofim** [comment]
Ты прав. У меня выключена анимация в интерфейсе gnome. И, непонятно почему, это распространяется на 2 браузера: firefox и gnome web. Анимацию включил в настройках и все закрутилось без проблем. Вот это номер) Спасибо!

**Comment by Vahan0799** [comment]
@dmitrytrofim Настройи все исправлены с моей позиции.  Можно обновлятся. 

При выключенном анимации, конфигурации все остаются кроме самой анимации бегущей строки.

`Debugger` опционалный и всегда выключен пока не активирван в самом настройке конфигурации.
