### ISSUE TITLE
Console log left in production

### ISSUE THREAD

**Issue by james0r** [Vahan0799/infinite-marquee#4]
<img width="613" alt="image" src="https://github.com/user-attachments/assets/03a006de-fe1a-49fd-9327-436ec6ae25be">

Using CDN
/**
 * Bundled by jsDelivr using Rollup v2.79.1 and Terser v5.19.2.
 * Original file: /npm/vanilla-infinite-marquee@1.0.10/infinite-marquee.mjs
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */

**Comment by Vahan0799** [comment]
Hi @james0r , thanks for the notice!

It's removed and deployed 😊
